### ISSUE TITLE
Error from a new clone of the project

### ISSUE THREAD

**Issue by curvenut** [ultrasonicsoft/gmap-ng5#8]
Hi

 I gotr the following error when I start the project : 

ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/bootstrap/dist/css/bootstrap.min.css
Module build failed: Error: Cannot find module 'cuint'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\home\dev\angular\gmap-angular5\gmap-ng5\node_modules\xxhashjs\lib\xxhash.js:7:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\home\dev\angular\gmap-angular5\gmap-ng5\node_modules\xxhashjs\lib\index.js:2:7)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
 @ ./node_modules/bootstrap/dist/css/bootstrap.min.css 4:14-131
 @ multi ./src/styles.css ./node_modules/bootstrap/dist/css/bootstrap.min.css

**Comment by ultrasonicsoft** [comment]
Hi,
Look likes you have not installed bootstrap and jQuery. Try to install it.

**Comment by ultrasonicsoft** [comment]
Did you solve it?
